### ISSUE TITLE
restart app.py to update cusswords.txt

### ISSUE THREAD

**Issue by Punit-Choudhary** [parnexcodes/Anti-abuse-api-flask#1]
`app.py` needs to be restarted whenever there's a change in cuss_words.txt for it to update the API.

There are two possible approach for this:
1. using a NLTK model trained to detect profanity sentences or words (no need of cusswords.txt then)
2. opening cusswords file in each check to fetch updates

Let me know which approach would you prefer.
Assign this issue to me, so that I can contribute to this repo 🙂💜 

Thanks

**Comment by parnexcodes** [comment]
Assigned , second approach preferred.
